import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

[shell]
  program = "/bin/zsh"
  # args = ["--login", "-c", "ranger"]

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font", style = "Bold Italic" }
size = 15.5

[cursor]
style = { shape = "Beam" }
vi_mode_style = { shape = "Block" }

[keyboard]
bindings = [
  { key = "V", mods = "Control", action = "ToggleViMode" },
  { key = "PageUp", mods = "Alt", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Alt", action = "ScrollPageDown" },
]

[window]
decorations = "Buttonless"
padding = { x = 20, y = 20 }

