# start at login
start-at-login = true

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout floating tiling'
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
alt-leftSquareBracket = 'resize smart -50'
alt-rightSquareBracket = 'resize smart +50'
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-left = 'move-node-to-monitor --wrap-around left'
alt-shift-right = 'move-node-to-monitor --wrap-around right'
alt-space = 'fullscreen'

# gaps between windows (inner-*) and between monitor edges (outer-*)
[gaps]
inner.horizontal = 20
inner.vertical =   20
outer.left =       20
outer.bottom =     20
outer.top =        25
outer.right =      20

