theme = 'dracula_at_night'

[editor]
line-number = "relative"
scrolloff = 8
shell = ["zsh"]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal.space]
s = ":w"
q = ":q"
Q = ":q!"
